rootProject.name = "midori"
include(":app:api")
include(":app:internal-api")
include(":app:rest-api")
include(":lib:app-common")
include(":lib:constant")
include(":lib:server-interceptor")
include(":lib:logger")
include(":lib:proto")
include(":lib:grpc-client")
